Update flutter-ci.yml

diff --git a/.github/workflows/flutter-ci.yml b/.github/workflows/flutter-ci.yml
--- a/.github/workflows/flutter-ci.yml
+++ b/.github/workflows/flutter-ci.yml
@@ -15,38 +15,43 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       
-      - uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.7.2'
-          channel: 'stable'
+#       - uses: subosito/flutter-action@v2
+#         with:
+#           flutter-version: '3.7.2'
+#           channel: 'stable'
           
-      - name: Flutter Version
-        run: flutter --version
+#       - name: Flutter Version
+#         run: flutter --version
       
-      #- name: Print Working Directory
-      #  run: pwd
+#       #- name: Print Working Directory
+#       #  run: pwd
       
-      - name: Get Dependencies
-        run: flutter pub get
+#       - name: Get Dependencies
+#         run: flutter pub get
 
-      - name: Run tests
-        run: flutter test
+#       - name: Run tests
+#         run: flutter test
+
+#       - name: Build apk
+#         run: flutter build apk
+        
+#       # Add the verification script here
+#       - name: Verify APK Build
+#         run: |
+#           if [ ! -f "/home/runner/work/assessment/assessment/build/app/outputs/flutter-apk/app-release.apk" ]; then
+#             echo "Error: APK not found at the specified path."
+#             exit 1
+#           fi
+#           echo "APK build verification successful."
+        
+#       - name: Upload Build apk to G-Drive
+#         uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
+#         with:
+#           target: /home/runner/work/assessment/assessment/build/app/outputs/flutter-apk/app-release.apk
+#           credentials: ${{ secrets.DRIVE_CREDENTIALS }}
+#           parent_folder_id: ${{ secrets.DRIVE_FOLDER_ID }}
+
 
       - name: Build apk
-        run: flutter build apk
-        
-      # Add the verification script here
-      - name: Verify APK Build
-        run: |
-          if [ ! -f "/home/runner/work/assessment/assessment/build/app/outputs/flutter-apk/app-release.apk" ]; then
-            echo "Error: APK not found at the specified path."
-            exit 1
-          fi
-          echo "APK build verification successful."
-        
-      - name: Upload Build apk to G-Drive
-        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
-        with:
-          target: /home/runner/work/assessment/assessment/build/app/outputs/flutter-apk/app-release.apk
-          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
-          parent_folder_id: ${{ secrets.DRIVE_FOLDER_ID }}
+        run: echo "Secret = "
+             echo ${{ secrets.DRIVE_FOLDER_ID }}
